language: python
python: 
  - "3.6"

install:
- pip install -r requirements.txt

env:
  global:
    - export APP_SETTINGS=testing

services:
  - postgresql

before_script:
    - source .env 
    - python db_setup.py

script:
  py.test --cov=api tests/

after_success:
  - coveralls
